apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: r8lxd40nc-go 
  janus-idp.io/tekton: r8lxd40nc-go
  backstage.io/kubernetes-id: r8lxd40nc-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: r8lxd40nc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml